apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix-container
        image: 528021155495.dkr.ecr.us-east-1.amazonaws.com/netflix:tagversion
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: netflix
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
